package com.macj7.loanapp.model;
// Generated Aug 15, 2015 2:59:02 AM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int custIdNo;
     private User user;
     private String custName;

    public Customer() {
    }

	
    public Customer(User user) {
        this.user = user;
    }
    public Customer(User user, String custName) {
       this.user = user;
       this.custName = custName;
    }
   
    public int getCustIdNo() {
        return this.custIdNo;
    }
    
    public void setCustIdNo(int custIdNo) {
        this.custIdNo = custIdNo;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }




}


