package com.macj7.loanapp.model;
// Generated Aug 15, 2015 2:59:02 AM by Hibernate Tools 4.3.1



/**
 * LoanOfficer generated by hbm2java
 */
public class LoanOfficer  implements java.io.Serializable {


     private int officerIdNo;
     private User user;
     private String officerName;

    public LoanOfficer() {
    }

	
    public LoanOfficer(User user) {
        this.user = user;
    }
    public LoanOfficer(User user, String officerName) {
       this.user = user;
       this.officerName = officerName;
    }
   
    public int getOfficerIdNo() {
        return this.officerIdNo;
    }
    
    public void setOfficerIdNo(int officerIdNo) {
        this.officerIdNo = officerIdNo;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getOfficerName() {
        return this.officerName;
    }
    
    public void setOfficerName(String officerName) {
        this.officerName = officerName;
    }




}


